### ISSUE TITLE
slow EMG_Raw rate

### ISSUE THREAD

**Issue by hananabilabd** [Alvipe/Open-Myo#2]
all i need to do is to handle the RAW EMG data like in main.py
and then pass it to a classifier which we have built ,,
My problem in main.py, that emg data frame is very slow , I receive 512 frame of emg every 20 sec which is very slow
while in windows running the [capture data](https://market.myo.com/app/55009793e4b02e27fd3abe79/myo-data-capture) provided by MYO_SDK gives me 3000 frame in 10 seconds 
so my question is , can open_myo do that on linux ?

**Comment by Alvipe** [comment]
This issue is about the sample rate of the [myo-raw](https://github.com/dzhu/myo-raw) code. Please, use the Open-Myo issues to report only those problems related to this code.
